name: Test Full Build
on:
  pull_request:
    branches:
      - nonexistent
    paths-ignore:
      - '**.md'
      - 'LICENSE'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Test Full Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win32,win64]
        variant: [gpl-shared,gpl-shared 5.1]
        include:
          - target: linux64
            variant: gpl
          - target: linux64
            variant: gpl 5.1
          - target: linuxarm64
            variant: gpl
          - target: linuxarm64
            variant: gpl 5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkit.toml
          driver: docker
      - name: Build Image
        run: ./makeimage.sh ${{ matrix.target }} ${{ matrix.variant }}
        env:
          QUICKBUILD: ${{ matrix.quickbuild }}
      - name: Build ffmpeg
        run: ./build.sh ${{ matrix.target }} ${{ matrix.variant }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg
          path: artifacts/*
